name: hotline
description: >-
  ActionCable client-like API in dart, for Dart and Flutter applications.
version: 1.1.0
homepage: https://github.com/phendrick/hotline
documentation: https://github.com/phendrick/hotline

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: ^3.0.5
  web_socket_channel: ^2.2.0

dev_dependencies:
  mockito: ^5.2.0
  build_runner: ^2.1.11
  lints: ^2.0.0
  test: ^1.21.0
