name: hotline
description: >-
  ActionCable client-like API in dart, for Dart and Flutter applications.
version: 1.0.3
homepage: https://github.com/phendrick/hotline
documentation: https://github.com/phendrick/hotline

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.0.0

dev_dependencies:
  mockito: ^5.0.2
  build_runner: ^1.11.0
  pedantic: ^1.9.0
  test: ^1.14.4
